#!/usr/bin/env node
// Build the platform packages from a release's prebuilt binaries and publish the
// whole set - the main package plus one os/cpu-restricted package per target.
// No install script anywhere (the esbuild / @biomejs pattern): npm installs only
// the platform package matching the machine, so there is no allow-scripts prompt.
//
// Usage:
//   node publish.mjs [<version>] [--dry-run]
//     <version>   defaults to the version in Cargo.toml.
//     --dry-run   builds + `npm pack`s into ./build, publishes nothing.
//
// Binaries come from https://github.com/youdie006/swapdex/releases/download/
//   v<version>/swapdex-<target>.tar.gz  (a release must exist for <version>).

import { execFileSync } from "node:child_process";
import { createRequire } from "node:module";
import {
  mkdirSync,
  writeFileSync,
  chmodSync,
  rmSync,
  readFileSync,
  copyFileSync,
  existsSync,
} from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const mainPkgPath = join(here, "package.json");
const mainPkg = JSON.parse(readFileSync(mainPkgPath, "utf8"));

const args = process.argv.slice(2);
const dryRun = args.includes("--dry-run");

// The version comes from Cargo.toml, which is the one place the release is
// declared. It used to default to this package.json's own version - but that
// field is REWRITTEN by this script on every publish, so after shipping 0.41.0
// a bare re-run tried to publish 0.41.0 again and npm refused. A second source
// of truth for a version number is how channels drift apart, so there is now
// only one, and a mismatch is a hard stop rather than a silent old release.
function cargoVersion() {
  const toml = readFileSync(join(here, "..", "Cargo.toml"), "utf8");
  const m = toml.match(/^version\s*=\s*"([^"]+)"/m);
  if (!m) throw new Error("no version found in Cargo.toml");
  return m[1];
}
const version = args.find((a) => !a.startsWith("--")) || cargoVersion();
const SCOPE = "@youdie006";

// swapdex is a Unix tool (Linux, WSL, macOS). musl binaries are static, so the
// one linux binary per arch serves both glibc and musl hosts.
const PLATFORMS = [
  { pkg: "swapdex-darwin-arm64", os: "darwin", cpu: "arm64", target: "aarch64-apple-darwin" },
  { pkg: "swapdex-darwin-x64", os: "darwin", cpu: "x64", target: "x86_64-apple-darwin" },
  { pkg: "swapdex-linux-x64", os: "linux", cpu: "x64", target: "x86_64-unknown-linux-musl" },
  { pkg: "swapdex-linux-arm64", os: "linux", cpu: "arm64", target: "aarch64-unknown-linux-musl" },
];

const sh = (cmd, cmdArgs, opts = {}) =>
  execFileSync(cmd, cmdArgs, { stdio: "inherit", ...opts });

const buildDir = join(here, "build");
rmSync(buildDir, { recursive: true, force: true });
mkdirSync(buildDir, { recursive: true });

// Keep the published main README in sync with the repo root README.
const rootReadme = join(here, "..", "README.md");
if (existsSync(rootReadme)) copyFileSync(rootReadme, join(here, "README.md"));

// 1) Build each platform package: the binary + an os/cpu-restricted manifest.
for (const p of PLATFORMS) {
  const dir = join(buildDir, p.pkg);
  mkdirSync(join(dir, "bin"), { recursive: true });
  const url = `https://github.com/youdie006/swapdex/releases/download/v${version}/swapdex-${p.target}.tar.gz`;
  const tgz = join(buildDir, `${p.target}.tar.gz`);
  sh("curl", ["-fSL", "-o", tgz, url]);
  sh("tar", ["-xzf", tgz, "-C", join(dir, "bin")]);
  const bin = join(dir, "bin", "swapdex");
  if (!existsSync(bin)) throw new Error(`archive for ${p.target} did not contain the binary`);
  chmodSync(bin, 0o755);
  rmSync(tgz);
  const manifest = {
    name: `${SCOPE}/${p.pkg}`,
    version,
    description: `Prebuilt swapdex binary for ${p.os}-${p.cpu}. Installed automatically by ${SCOPE}/swapdex; do not depend on it directly.`,
    license: mainPkg.license,
    repository: mainPkg.repository,
    homepage: mainPkg.homepage,
    os: [p.os],
    cpu: [p.cpu],
    files: ["bin/swapdex"],
  };
  writeFileSync(join(dir, "package.json"), JSON.stringify(manifest, null, 2) + "\n");
}

// 1b) The man page, generated by the binary itself so it can never drift from
//     the command set. It goes in the MAIN package - that is the one npm always
//     installs, and npm links a `man` entry on a global install, so `man swapdex`
//     works however swapdex was installed and not only through Homebrew.
{
  const host = PLATFORMS.find(
    (p) =>
      p.os === process.platform &&
      p.cpu === (process.arch === "arm64" ? "arm64" : "x64")
  );
  if (!host) {
    throw new Error(
      `no prebuilt binary for this build host (${process.platform}-${process.arch}); ` +
        "the man page is generated by running one, so publish from a supported host"
    );
  }
  const roff = execFileSync(join(buildDir, host.pkg, "bin", "swapdex"), ["manpage"], {
    maxBuffer: 8 << 20,
  });
  if (!roff.includes(".TH")) throw new Error("swapdex manpage did not produce a roff page");
  mkdirSync(join(here, "man"), { recursive: true });
  writeFileSync(join(here, "man", "swapdex.1"), roff);
}

// 2) Pin the main package's version + optionalDependencies to this version.
mainPkg.version = version;
mainPkg.optionalDependencies = Object.fromEntries(
  PLATFORMS.map((p) => [`${SCOPE}/${p.pkg}`, version])
);
writeFileSync(mainPkgPath, JSON.stringify(mainPkg, null, 2) + "\n");

// 3) Publish platform packages FIRST (so the main's optionalDependencies
//    resolve on the registry), then the main. --dry-run packs instead.
const npmArgs = dryRun
  ? ["pack", "--pack-destination", buildDir]
  : ["publish", "--access", "public"];
for (const p of PLATFORMS) sh("npm", npmArgs, { cwd: join(buildDir, p.pkg) });
sh("npm", npmArgs, { cwd: here });

// Wait for the registry to actually SERVE what was just published. `npm
// publish` returning means the write was accepted, not that a reader can
// resolve it - so an install run seconds later fails with ETARGET ("No matching
// version found") for a version that exists. That happened on every release,
// and each time it read as a broken install rather than a slow registry.
const { publishSummary, wantedSpecs } = createRequire(import.meta.url)("./summary.js");
const unresolved = [];
if (!dryRun) {
  const wanted = wantedSpecs(SCOPE, PLATFORMS, version);
  for (const spec of wanted) {
    // Per package, not one budget shared by all of them. It was computed once
    // before this loop, so four packages that each took thirty seconds left
    // the fifth none at all - which is how a release went out with one
    // platform package unpublished.
    const deadline = Date.now() + 120_000;
    for (;;) {
      let seen = "";
      try {
        seen = execFileSync("npm", ["view", spec, "version"], {
          encoding: "utf8",
          stdio: ["ignore", "pipe", "ignore"],
        }).trim();
      } catch {
        seen = "";
      }
      if (seen === version) break;
      if (Date.now() > deadline) {
        unresolved.push(spec);
        break;
      }
      execFileSync("sleep", ["3"], { stdio: "ignore" });
    }
  }
}

if (dryRun) {
  console.log(`\nDRY RUN complete: tarballs in ${buildDir}, nothing published.`);
} else {
  const { text, ok } = publishSummary(version, PLATFORMS.length, unresolved);
  console.log(text);
  // Non-zero, so a release that half-landed cannot be mistaken for one that
  // did - including by a caller that only reads the last line.
  if (!ok) process.exit(1);
}
